### ISSUE TITLE
Disable logging of entire config file

### ISSUE THREAD

**Issue by aegliv** [cloudfoundry/nginx-buildpack#125]
Could you please provide an option for disabling this log:

https://github.com/cloudfoundry/nginx-buildpack/blob/f039d86b1995a9241eff7641d2309889610e15f9/src/nginx/varify/cli/varify.go#L131

It is very noisy and not need once the config works

**Comment by brayanhenao** [comment]
Hi @aegliv, thanks for your interest in the Buildpack!

We reviewed this problem with the team and decided that this line of code was indeed producing an output in the logs that was very noisy. Right now these changes are in the [`develop`](https://github.com/cloudfoundry/nginx-buildpack/commit/f898777aaa8e9219e9538ada73e199b89774589d) branch and will be in the main branch for the next release of `Nginx Buildpack` around the first week of April.

**Comment by brayanhenao** [comment]
@aegliv Nginx Buildpack [`v1.1.37`](https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.1.37) released with the noisy logging removed!
