### ISSUE TITLE
Provided nginx binary does not include ngx_http_sub_module module compiled. 

### ISSUE THREAD

**Issue by RageZBla** [cloudfoundry/nginx-buildpack#14]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version 6.40.0+07673feb9.2018-10-08

What version of the buildpack you are using?

v1.0.5

If you were attempting to accomplish a task, what was it you were attempting to do?

Try to use `sub_filter` directive in `nginx.conf`

What did you expect to happen?

`sub_filter` directive should be working.

What was the actual behavior?

BP rejects the `nginx.conf` when linting the configuration file because module is not provided/enabled.

To reproduce try to push any configuration file using the `sub_filter` directive.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by kardolus** [comment]
Hi @RageZBla, thanks for reaching out to the team.

I looked at this briefly and am not sure where to specify the `sub_filter` directive. When I put it under `server` like this: 

```
  server {
    listen {{port}};
    root public;
    index index.html index.htm Default.htm;
    sub_filter 'original_string' 'replacement_string';
  }
```

I get the following error: `2019/02/26 20:43:24 [emerg] 29#0: unknown directive "sub_filter" in /tmp/conf405523364/nginx.conf:23`

Is this the error you are seeing? Could you provide us with the logs and could you help us with the sub_filter directive? (Where is it declared)

Thanks!

**Comment by Zanadar** [comment]
@RageZBla Thanks for filing this. For the moment, we don't build with this module, although we're certainly open to adding it (See https://github.com/cloudfoundry/binary-builder/blob/master/recipe/nginx.rb#L5 for a list of modules we include). Can you give us some idea of your use case (just to give us a sense of what you're using it for)?

**Comment by RageZBla** [comment]
@Zanadar my use case was to fix some broken invalid links from the backend application. Without this module, it makes it difficult to consider the proxied application as a black box.

**Comment by pburkholder** [comment]
Exact same issue here, would like to have this module. Thanks!

**Comment by tylerphelan** [comment]
This module should be available on the `develop` branch if you want to give it a try. It will be in the next release of the buildpack. Let us know if you see any issues.
