### ISSUE TITLE
lua package install

### ISSUE THREAD

**Issue by amaline** [cloudfoundry/nginx-buildpack#18]
Is there a standard way of installing lua packages with opm in the buildpack when using the openresty distribution?

**Comment by Zanadar** [comment]
@amaline We'll look into this.

**Comment by shanks3012** [comment]
@amaline We are currently in the process of replacing the nginx buildpack and are working on building out the xnginx functionality in that new buildpack. At this time, we do not have the bandwidth to implement this for the current nginx buildpack. If this is still a need when the nginx Cloud Native Buildpack is released, please feel free to reopen the issue. Thanks!

**Comment by mamacdon** [comment]
Did anyone find an answer to this? The nginx-cnb buildpack doesn't seem to be production ready…
