### ISSUE TITLE
Release: nginx-buildpack (Feb)

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/nginx-buildpack#183]
Release reminder!
Also make sure you pull in the `Release Reminder` workflow before release so that it automates this issue creation!

**Comment by brayanhenao** [comment]
PR: https://github.com/cloudfoundry/nginx-buildpack/pull/187
Release tag: [v1.2.0](https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.2.0)
