### ISSUE TITLE
NewRelic Integration

### ISSUE THREAD

**Issue by elgohr** [cloudfoundry/nginx-buildpack#19]
As the slack channel is archived, I'm using this as a way to ask whether a PR with NewRelic Integration would be welcome?

**Comment by tillyt** [comment]
Yes, feel free to create a PR and we will look it over! 

For some more context, we're currently in the process of working on cloud-native buildpacks, which would have New Relic separate from nginx buildpack but those won't be ready to use soon and if you need New Relic in the meantime, a PR is the way to go
