### ISSUE TITLE
Release: nginx-buildpack (Mar)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/nginx-buildpack#198]
Release reminder for nginx-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/nginx-buildpack/compare/v1.2.0..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/nginx-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by arjun024** [comment]
https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.2.1
