### ISSUE TITLE
Feature Request: Add built-in Perl module 

### ISSUE THREAD

**Issue by saescha** [cloudfoundry/nginx-buildpack#22]
Hi folks,

We could use some scripting capabilities in our NGINX proxy app. I know it is possible to upload custom modules by ourselves. But it is kind of inconvenient, because you need to compile it with the corresponding NGINX version. And I think this module has a wide usage and could be also useful for other consumers.
Unfortunately I don't see a way to create a pull request for this, as the modules are delivered as binary and served from https://buildpacks.cloudfoundry.org/dependencies/nginx/ 

I suggest to build and deliver http://nginx.org/en/docs/http/ngx_http_perl_module.html as built-in module, as it is the most common one. But any scripting module would do.

reg.
Sascha

**Comment by martyspiewak** [comment]
Hi, sorry for the extended delay.

Openresty is included in the buildpack and includes this module.
