### ISSUE TITLE
{{port}} replacement also for include files

### ISSUE THREAD

**Issue by Dellle** [cloudfoundry/nginx-buildpack#23]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
API-Version: 2.143.0
cf Version 6.46.1

What version of the buildpack you are using?
Nginx Buildpack version 1.1.2

If you were attempting to accomplish a task, what was it you were attempting to do?
I wanted to split the nginx.conf files in some sub-files to get a better structure.
So I include them in the main nginx.conf file with `include nginx-conf/*.conf;`

What did you expect to happen?
I expect that {{port}} replacement is also working for the included files from the subfolder.

What was the actual behavior?
{{port}} replacement is only done for the nginx.conf file.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by arjun024** [comment]
This is available from nginx `v1.1.21` onwards.
