### ISSUE TITLE
{{nameservers}} not working in nginx.conf

### ISSUE THREAD

**Issue by kodemus** [cloudfoundry/nginx-buildpack#24]
- What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
cf curl /v2/info && cf version
{
   "name": "xxx",
   "build": "",
   "support": "",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://xxx",
   "token_endpoint": "https://xxx",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "xxx:2210",
   "app_ssh_host_key_fingerprint": "xxx",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.xxx:443",
   "api_version": "2.141.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.xxx/routing",
   "user": "xxx"
}
cf version 6.47.2+d526c2cb3.2019-11-05
```

- What version of the buildpack you are using?

nginx_buildpack_v1_1_3

- If you were attempting to accomplish a task, what was it you were attempting to do?

I want to push an application with the nameserver injected by cf as described here : [`{{nameservers}}` - support for CF internal domain resolver](https://github.com/cloudfoundry/nginx-buildpack/pull/12)

My code in nginx.conf is : 
```
http {
  resolver {{nameservers}};
}
```

- What did you expect to happen?

I expect the dns servers to be extracted from /etc/resolv.conf and injected in the nginx.conf file. It would then become :
```
http {
  resolver 169.254.0.2;
}
```

- What was the actual behavior?

The application is not pushed and the following error occurs :
```
   -----> Supplying nginx
   -----> Requested nginx version: mainline => 1.17.7
   -----> Installing nginx 1.17.7
          Copy [/tmp/buildpacks/1773a27b0739b86b0235a214427fbd94/dependencies/502c9539995224def16e6d4673147ac1/nginx-1.17.7-linux-x64-cflinuxfs3-718363fe.tgz]
          **ERROR** Could not write tmp config file: template: conf:35:13: executing "conf" at <nameservers>: wrong number of args for nameservers: want 1 got 0
          **ERROR** Could not validate nginx.conf: template: conf:35:13: executing "conf" at <nameservers>: wrong number of args for nameservers: want 1 got 0
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
   Exit status 223
```

As far as I understand, the issue comes from the file src/nginx/supply/supply.go, line 266 :
```
"nameservers": func(arg string) string
```
instead of
```
"nameservers": func() string
```
as specified in file src/nginx/varify/varify.go, line 92 :
```
"nameservers": func() string
```

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by kinjelom** [comment]
@kodemus You're right, it was a bug.
Please test it with the fixed buildpack:
```
cf push theapp -b https://github.com/i6e/nginx-buildpack.git
cf ssh theapp -c "cat app/nginx.conf | grep resolver"
```
I'll do PR.

**Comment by ryanmoran** [comment]
I'm going to close this since the PR was resolved. Thanks!
