### ISSUE TITLE
Read environment variables provided in manifest.yml in angular app

### ISSUE THREAD

**Issue by ybanda** [cloudfoundry/nginx-buildpack#40]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
6.32

What version of the buildpack you are using?
Cflinux s3-v1.5.6

If you were attempting to accomplish a task, what was it you were attempting to do?
Try to reading environment variables mentioned in the manifest.yml from an angular app.
I dont see any proper documentation to achieve this pcf 

What did you expect to happen?
Read environment variables just like java buildpacks

What was the actual behavior?
I dont know whether this is supported by static buildpack or not

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by Lonli-Lokli** [comment]
@ybanda 
you can specify this in nginx.conf and read 'appsettings' URL from your application
```
 server {
    
    location / {
    
      <% if ENV["APP_CONFIGURATION"] %>
      location /appsettings {
          default_type application/json;
          return 200 '<%= ENV["APP_CONFIGURATION"] %>';
      }
      <% end %>
    }
  }
```

and in your manifest file just add this settings
```
env:
    APP_CONFIGURATION: '{
      "settings1": "value1",
      "parent": {
        "child": "value2"
      }
    }'
```

**Comment by ybanda** [comment]
@Lonli-Lokli - do you have a sample by any chance. do i need to update the build from static_buildpack to nginx_buildpack.

**Comment by joshzarrabi** [comment]
@ybanda  I just tried this out with success:

```bash
 ‣ cat manifest.yml
---
applications:
  - name: what_does_it_do
    env:
      MANIFEST_VARIABLE: "VARIABLE_IS_SET"
```

```bash
 ‣  cat nginx.conf
worker_processes 1;
daemon off;

error_log stderr;
events { worker_connections 1024; }

http {
  charset utf-8;
  log_format cloudfoundry 'NginxLog "$request" $status $body_bytes_sent';
  access_log /dev/stdout cloudfoundry;
  default_type application/octet-stream;
  include mime.types;
  sendfile on;

  tcp_nopush on;
  keepalive_timeout 30;
  port_in_redirect off; # Ensure that redirects don't include the internal container PORT - 8080

  server {
    listen {{port}};
    root public;
    index index.html index.htm Default.htm;

    # configuration endpoint
    location /test {
      default_type application/json;

      set $override "{{env "MANIFEST_VARIABLE"}}";

      if ($override != '') {
          return 200 "{{env "MANIFEST_VARIABLE"}}";
      }

      return 200 "No overrides happening! \"abc\"";
    }
  }
}
```

**Comment by mygitbotnew** [comment]
@joshzarrabi  joshzarrabi : could you please show example how you use your MANIFEST_VARIABLE in your angular code? And VARIABLE_IS_SET is looks static. My requirement is this value is different for each env I mean Dev/QA/PROD. Can we use $ symbol for this variable like ${env.sqlconn} in manifest.yml?

**Comment by mygitbotnew** [comment]
Do we need to manually copy manifest.yml and nginx.conf in dist folder?
