### ISSUE TITLE
Can we provide the nginx that compiled with --with-compat?

### ISSUE THREAD

**Issue by wdxxs2z** [cloudfoundry/nginx-buildpack#5]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
api version:    2.82.0
```

What version of the buildpack you are using?
```
1.0 release
```
If you were attempting to accomplish a task, what was it you were attempting to do?

**the nginx config:**
```
load_module ngx_http_sticky_module.so;
```
**logs:**
```
   Installing nginx 1.15.1 Copy [/tmp/buildpacks/7f788470eaeb01f14116979c44aca71a/dependencies/1b46fe5e44de44070849a0d8e5c44c4d/nginx-1.15.1-linux-x64-e81efce1.tgz]
   2018/07/25 11:57:58 [emerg] 23#0: module "/tmp/conf606264057/ngx_http_sticky_module.so" is not binary compatible in /tmp/conf606264057/nginx.conf:1
   nginx: configuration file /tmp/conf606264057/nginx.conf test failed
```
What did you expect to happen?

1. nginx can load user provider dynamic module, and nginx itself should also be compiled with --with-compat option

What was the actual behavior?

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by astrieanna** [comment]
@wdxxs2z This is a good idea; thanks for pointing that build option out.

**Comment by jfeeny** [comment]
Hey @wdxxs2z sorry for the delay on this. Would you be able to provide a sample app?

**Comment by wdxxs2z** [comment]
Hey, @jfeeny , i use the nginx (https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng) module, and complied with our nginx-buildpack' nginx version, the template such as:

--- modules
      |---ngx_http_sticky_module.so
--- index.html
--- mine.types
--- nginx.conf

```
{{if .SessionSticky}}
load_module ngx_http_sticky_module.so;
{{end}}

worker_processes 1;
daemon off;

error_log stderr;
events { worker_connections 1024; }

http {
  charset utf-8;
  log_format cloudfoundry '$http_x_forwarded_for - $http_referer - [$time_local] "$request" $status $body_bytes_sent';
  access_log /dev/stdout cloudfoundry;
  default_type application/octet-stream;
  include mime.types;
  sendfile on;

  gzip on;
  gzip_disable "msie6";
  gzip_comp_level 6;
  gzip_min_length 1100;
  gzip_buffers 16 8k;
  gzip_proxied any;
  gunzip on;
  gzip_static always;
  gzip_types text/plain text/css text/js text/xml text/javascript application/javascript application/x-javascript application/json application/xml application/xml+rss;
  gzip_vary on;

  tcp_nopush on;
  keepalive_timeout 30;
  port_in_redirect off;
  server_tokens off;

  {{range .Nginxs}}
      server {
        listen {{ .Port}};
        server_name {{ .Name}};
        location / {
            proxy_pass       http://{{ .Url}};
            proxy_set_header Host {{ .Url}};
         }
      }
  {{end}}

  {{ $length := len .Nginxs }} {{ if ne $length 0 }}
  upstream {{ .ServiceId}} {
    {{if .SessionSticky}}
    sticky expires=1h;
    {{else}}
    keepalive 2000;
    {{end}}
    {{range .Nginxs}}
    server 127.0.0.1:{{ .Port}}  weight={{ .Weight}};
    {{end}}
  }
  {{end}}

  server {
    listen {{"{{port}}"}};
    server_name localhost;

    location / {
      proxy_redirect off;
      {{ $length := len .Nginxs }} {{ if ne $length 0 }}
      proxy_pass http://{{ .ServiceId}};
      {{else}}
      root /home/vcap/app;
      index index.html index.htm Default.htm;
      {{end}}
    }

    location ~ /\. {
      deny all;
      return 404;
    }
  }
}
```

**Comment by Ben16** [comment]
Hi @wdxxs2z,
We were able to re-produce your issue, and we've pushed a fixed to the `develop` branch. Feel free to try it out; it should be a part of the next release as well. I'm going to go ahead and close this issue but if you have any further issues please feel free to re-open it.

**Comment by ameyer-pivotal** [comment]
@wdxxs2z New update: On the next release, you'll be able to use the following syntax if you place your module in a `modules` directory (otherwise you can use the native `load_module` directive as you're doing now):

```{{module "ngx_http_sticky_module"}}```

Changes are on `develop` if you'd like to test now. Also, our [nginx buildpack docs](https://docs.cloudfoundry.org/buildpacks/nginx/index.html) will be updated to reflect the changes, so be sure to check back on them in a few days.
