### ISSUE TITLE
http to https redirect not working

### ISSUE THREAD

**Issue by krishansaini92** [cloudfoundry/nginx-buildpack#53]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "Name",
   "build": "2.10.5-build.14",
   "version": 0,
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_oauth_client": "ssh-proxy",
   "api_version": "2.150.0",
   "osbapi_version": "2.15"
}
cf version 7.2.0+be4a5ce2b.2020-12-10

What version of the buildpack you are using?
v1.1.20

If you were attempting to accomplish a task, what was it you were attempting to do?
redirect all http requests to https.

What did you expect to happen?
It should have redirected from http to https

What was the actual behavior?
Struggling to redirect http to https using nginx config. Please let us know if anyone has done the same using nginx-buildpack.
I have even used the same nginx config as generated by staticfile-buildpack with Force-https true. That has also not worked.

Please confirm where necessary:
* [ ] I have included a log output - No logs for http requests
* [ ] My log includes an error message - No error message
* [ ] I have included steps for reproduction - Attaching the nginx.conf file below.

**NGINX.CONF**

```
worker_processes 1;
daemon off;

error_log stderr;
events { worker_connections 1024; }

http {
  charset utf-8;
  log_format cloudfoundry 'NginxLog "$request" $status $body_bytes_sent';
  access_log /dev/stdout cloudfoundry;
  default_type application/octet-stream;
  include mime.types;
  sendfile on;

  tcp_nopush on;
  keepalive_timeout 30;
  port_in_redirect off; # Ensure that redirects don't include the internal container PORT - 8080

  # server {
  #   listen 80;
  #   server_name _;
  #   return 301 https://$host$request_uri;
  # }

  server {
    listen {{port}};
    root /app;
    index index.html index.htm Default.htm;

    set $updated_host $host;
    if ($http_x_forwarded_host != "") {
      set $updated_host $http_x_forwarded_host;
    } 

    if ($http_x_forwarded_proto != "https") {
      return 301 https://$updated_host$request_uri;
    }

    # configuration endpoint

    location /test {
      default_type application/json;

      set $override "{{env "OVERRIDE"}}";

      if ($override != '') {
          return 200 "{{env "OVERRIDE"}}";
      }

      return 200 "No overrides happening! \"abc\"";
    }

    location /SAAS {
      proxy_pass some_url;
      proxy_http_version 1.1;
    }

    location /oauthtoken {
      proxy_pass some_url;
      proxy_http_version 1.1;
    }

    location / {
      try_files $uri $uri/ /index.html;

      root /app;
      index index.html index.htm;
    }
  }
}
```

**Comment by menehune23** [comment]
Hi @krishansaini92, I'm closing this issue as stale, but feel free to reopen if you'd still like help with this. If you do, please include a link to a minimal app repo that reproduces the problem, along with detailed reproduction steps. Thanks!
