### ISSUE TITLE
Support template parsing for mask in nginx.conf include directive

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/nginx-buildpack#56]
See http://nginx.org/en/docs/ngx_core_module.html#include, it supports masks like `include vhosts/*.conf;` in the `include` directive. Could that be supported in the templating?

See https://github.com/cloudfoundry/nginx-buildpack/commit/2fe000359e82de2c9fbdc0b19c2a1c6f11009034 where templating for `include` files were supported but not masks.

**Comment by johnnyr0x** [comment]
Should be a small feature. Have we had any user ask for this?

**Comment by arjun024** [comment]
There's this PR I had done earlier towards this feature but I can't remember how complete it is
https://github.com/cloudfoundry/nginx-buildpack/pull/58

I'll close the issue for now as users haven't asked for this, but all community users should free to reuse the code in the above PR if this is a feature they consider valuable
