### ISSUE TITLE
Enable removing all Server header information

### ISSUE THREAD

**Issue by kr8n3r** [cloudfoundry/nginx-buildpack#57]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
2.161.0
cf version 7.2.0+be4a5ce2b.2020-12-10

```

What version of the buildpack you are using?

`v1.17.10`

If you were attempting to accomplish a task, what was it you were attempting to do?

Completely remove Server information from the response.

What did you expect to happen?

Expect to be able to do so natively in with the buildpack.
Removing all header information relating to the nginx installation requires compiling the `ngx_http_header_filter_module` or use of third-party modules, namely `nginx-module-security-headers` or, `nginx-module- headers-more, neither of which are statically compiled as per https://docs.cloudfoundry.org/buildpacks/nginx/index.html#loading-modules

What was the actual behavior?

Noop

**Comment by arjun024** [comment]
The `ngx_http_security_headers_module.so` is not provided with the buildpack. So you need to download the shared-library file and put it in a `modules` directory at the root of your app.
Now you may use `{{module "ngx_http_security_headers_module"}}` in your config file. It's for buildpack provided modules (seen in the link you provided) that you do not need to provide the file yourself. Feel free to reopen the issue if that didn't solve your problem

**Comment by kr8n3r** [comment]
Hi, thanks for the response.
While there is an option to compile those modules and include it in an individual app, it would be better if this was part of the buildpack so it available for any user to enable it without compiling.
