### ISSUE TITLE
Create BOSH release

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/nginx-buildpack#7]
As a Cloud Foundry operator, I want to include the nginx buildpack along with the other system buildpacks. I see that this repo includes buildpack archives along with releases, but other system buildpacks are distributed as bosh releases via bosh.io. Would you be open to distributing this as a bosh release as well?

**Comment by jmcarp** [comment]
I made a release at https://github.com/jmcarp/nginx-buildpack-release. It's trivial to set up, but I'd be happy to transfer the repo over to you if you'd like.

**Comment by jfeeny** [comment]
@jmcarp Hi, and thanks for the request. We have a [story in our backlog](https://wwiw.pivotaltracker.com/story/show/159444623) for this. We'll let you know when it gets worked on, though we can't give an estimate at this point. @sclevine Anything to add?

**Comment by sclevine** [comment]
We will create a BOSH release for this when it gets added to cf-deployment.

**Comment by heyjcollins** [comment]
Hey @sclevine - this is a chicken/egg situation - we'd like for it to be on bosh.io in order to include it in cf-deployment.

**Comment by Zanadar** [comment]
This is done. Closing the issue.
