### ISSUE TITLE
Investigate why bot auto-removes version lines

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/nginx-buildpack#72]
**Problem**

nginx 1.18 version line was removed [by the bot](https://github.com/cloudfoundry/nginx-buildpack/commit/3d33159135ccc4244c45ac078668c7d7d28d3060) triggered by the [pipeline job](https://buildpacks.ci.cf-app.com/teams/main/pipelines/dependency-builds/jobs/update-nginx-1.20.x-nginx/builds/1).

Looking at [the history](https://github.com/cloudfoundry/nginx-buildpack/commits/master), it seems like the automation auto-removes older minor versions (version lines) when new minors are available, and Core-deps/buildpacks team had to manually re-add it (e.g. [re-adding 1.16](https://github.com/cloudfoundry/nginx-buildpack/commit/cf1de0a6463b14d85173b5e5ee7ad875a64a5875), [re-adding 1.17](https://github.com/cloudfoundry/nginx-buildpack/commit/2eb01c5520e9ccbe6211824b7e160fc4d42eb0ee)) after the bot removes them.

This causes buildpack versions to be shipped with versions removed without proper notice if they are not manually noticed and taken action. [v1.1.25](https://github.com/cloudfoundry/nginx-buildpack/releases/tag/v1.1.25) removed support for v1.18 version line without due notice.

**Investigate**

Investigate why the nginx automation/bot removes older version lines when new version lines are added.
Removal of version lines are done manually and automation shouldn't remove version lines.
This issue doesn't seem to be happening in buildpacks like [go-buildpack](https://github.com/cloudfoundry/go-buildpack) that has similar version lines.

edit: A note about go

**Comment by shanks3012** [comment]
Generally, our automation sees minor versions not as new version lines and will only carry the most recent 2 minor versions. This seems to be what is happening here, but rather minors are their own version lines for nginx. We should look to see if it is possible to hold this pattern on the patch versions for nginx and have minor versions be seen as their own version lines enabling as many active minor versions at a time as possible.

**Comment by arjun024** [comment]
So I am looking into the pipeline design and here are the findings:
 * It looks like buildpack team has always considered "nginx dependency in the nginx buildpack" to be [a special type](https://github.com/cloudfoundry/buildpacks-ci/blob/fc755d521a858b588dddd3d0203363360efce686/pipelines/dependency-builds.yml.erb#L519).
 * This nginx special type only has [2 version lines: stable & mainline](https://github.com/cloudfoundry/buildpacks-ci/blob/fc755d521a858b588dddd3d0203363360efce686/tasks/update-buildpack-dependency/run.rb#L156-L158).
 * That is: `1.13.X and 1.15.X are the same version line` and ` 1.12.X and 1.14.X are the same version line`. This is the reason why the [pipeline job removes the older minor while adding a new minor](https://github.com/cloudfoundry/buildpacks-ci/blob/fc755d521a858b588dddd3d0203363360efce686/tasks/update-buildpack-dependency/dependencies.rb#L67-L72).
 * Looks like this strategy has been on since 2018 ([commit](https://github.com/cloudfoundry/buildpacks-ci/commit/c4123755e47399ecae70f5e5a64c56f5021172aa), [tracker](https://www.pivotaltracker.com/n/projects/1042066/stories/155035352)).
 * This strategy thus makes sure that we have exactly 1 stable and exactly 1 mainline versions available in the buildpack.
 * I analyzed nginx version line change history (e.g. http://nginx.org/en/CHANGES-1.18) and it doesn't look like they patch older versions of stable or mainline. So keeping older stable/mainline versions in the buildpack do not seem right. Thus rolling version lines of stable and mainline makes sense.
 ---
 
 @shanks3012 The only cog that doesn't seem to fit nicely is the 30 day deprecation notices for minors inside a version line. If we have a commitment to provide 30 day notice for a change like 1.13.x -> 1.15.x, team members have to be conscious of this automation and not release such a change until the notice period is over. If we do have that commitment, then we can add that to the v2b release issue checklist so that we don't release without notice. What do you think?
@kvedurmu

**Comment by shanks3012** [comment]
Closing this out as we will no longer be sending deprecation notices going forward. We can allow these pipelines to continue operating as they do
