### ISSUE TITLE
IMPORTANT NOTICE: [nginx-buildpack] Change of default nginx version after 2021-07-09

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/nginx-buildpack#79]
The default version for NGINX will be updated to 1.21.x in the first release of the NGINX buildpack after 2021-07-09.

We are giving a 30 day notice to inform users that the default version of NGINX in the NGINX buildpack will be updated to the latest 1.21.x version in the first release of the NGINX buildpack after 2021-07-09.

If you’d like to use a different NGINX version, please configure your application to select that version.[1]

As always, the buildpacks team is happy to answer questions you may have about this deprecation in the #buildpacks Slack channel[2].

[1] - https://docs.cloudfoundry.org/buildpacks/nginx/index.html
[2] - https://cloudfoundry.slack.com/archives/C02HWMDUQ

Thanks,
The Buildpacks Team

**Comment by AccraZed** [comment]
since there was a critical vulnerability found with versions <1.19, changes are effective immediately. see #87
