### ISSUE TITLE
NGINX buildpack and DNS

### ISSUE THREAD

**Issue by giner** [cloudfoundry/nginx-buildpack#8]
By default NGINX resolves DNS for upstream hosts [only once](https://www.nginx.com/blog/dns-service-discovery-nginx-plus/) (on start) which is not always suitable. Using staticfile buildpack it was possible to make NGINX use system dns using the following "hack":
```
  <% RESOLVERS = ( require 'resolv'; Resolv::DNS::Config.default_config_hash[:nameserver].join(" ") ) %>
  resolver <%= RESOLVERS %> ipv6=off; # unused if backends are specified as IPs
```

It seems to be impossible to do the same with nginx-buildpack. Any suggestions?

**Comment by jfeeny** [comment]
Hi @giner. Thanks for bringing this up. @sclevine Do you know how this might be achieved in the `nginx-buildpack`?

**Comment by sclevine** [comment]
Apologies for the delay here. You should be able to do this using the `{{ env "VAR" }}` templating function. So that you don't have to `cf set-env` the DNS resolvers manually, you could use `.profile` file in the app directory to pull the resolvers from the container system settings (e.g., from `/etc/resolve.conf`).

**Comment by ameyer-pivotal** [comment]
@giner I'll go ahead and close this. If you try out @sclevine's suggestion and are still having problems, feel free to re-open.

**Comment by wildloop** [comment]
Workaround (#12): 
```yml
http {
  server {
    listen {{port}};
    resolver 169.254.0.2; 
    # default `nameserver` is `169.254.0.2` and it doesn't change without reconfiguration
    # https://github.com/cloudfoundry/bosh-dns-release/blob/master/jobs/bosh-dns/spec#L36-L38
```

**Comment by giner** [comment]
> resolver 169.254.0.2;

This requires a developer to know configuration of the platform which may not be the same everywhere.

**Comment by yuanli-cn** [comment]
> Apologies for the delay here. You should be able to do this using the `{{ env "VAR" }}` templating function. So that you don't have to `cf set-env` the DNS resolvers manually, you could use `.profile` file in the app directory to pull the resolvers from the container system settings (e.g., from `/etc/resolv.conf`).

Hi sclevine,
Can you explain how can nginx.conf refers to the variable exported in .profile? I tried to use `{{env "VAR"}}`, but fails.
Thanks
